steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/radhe-resume:$COMMIT_SHA', '-f', 'Dockerfile', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/radhe-resume:$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'radheresume'
  - '--image'
  - 'gcr.io/$PROJECT_ID/radhe-resume:$COMMIT_SHA'
  - '--region'
  - 'us-central1'